#helmet
#dataset_root: '/home/cv/AI_Data/HardHatWorker_voc'
#model_path: 'model_data/helmet.pt' #模型权重路径
#classes_path: 'model_data/helmet_classes.yaml' #数据类别文件
#anchors_path: 'model_data/HardHatWorker_anchors.yaml' #数据集anchors文件

#HardHatWorker_voc
#dataset_root: '/home/cv/AI_Data/HardHatWorker_voc'
#model_path: 'model_data/HardHatWorker.pth' #模型权重路径
#classes_path: 'model_data/HardHatWorker_classes.yaml' #数据类别文件
#anchors_path: 'model_data/HardHatWorker_anchors.yaml' #数据集anchors文件

#person
#dataset_root: '/home/cv/AI_Data/person_yolo'
#dataset_root: '/home/cv/AI_Data/HardHatWorker_voc'
#model_path: 'model_data/person.pth' #模型权重路径
#classes_path: 'model_data/person_classes.yaml' #数据类别文件
#anchors_path: 'model_data/person_anchors.yaml' #数据集anchors文件

#widerface
#dataset_root: '/home/cv/AI_Data/yolo_widerface_open_train'
#model_path: 'model_data/widerface.pt' #模型权重路径
#classes_path: 'model_data/widerface_classes.yaml' #数据类别文件
#anchors_path: 'model_data/widerface_anchors.yaml' #数据集anchors文件

#coco
#dataset_root: '/home/cv/AI_Data/yolo_widerface_open_train'
#model_path: 'model_data/coco.pt' #模型权重路径
#classes_path: 'model_data/coco_classes.yaml' #数据类别文件
#anchors_path: 'model_data/coco_anchors.yaml' #数据集anchors文件

#voc
#dataset_root: '/home/cv/AI_Data/VOCtest2007'
#model_path: 'model_data/voc.pth' #模型权重路径
#classes_path: 'model_data/voc_classes.yaml' #数据类别文件
#anchors_path: 'model_data/voc_anchors.yaml' #数据集anchors文件

#hat_worker_voc
#dataset_root: '/home/cv/AI_Data/hat_worker_voc' #数据集根目录
#model_path: 'logs/hat_worker_voc-ep098-loss3.201-val_loss3.313.pth' #模型权重路径
#classes_path: 'model_data/hat_worker_classes.yaml' #数据类别文件
#anchors_path: 'model_data/hat_worker_anchors.yaml' #数据集anchors文件

#head_test
dataset_root: '/home/cv/AI_Data/head_datas_yolo' #数据集根目录
model_path: 'model_data/head.pth'
classes_path: 'model_data/head_classes.yaml' #数据类别文件
anchors_path: 'model_data/head_anchors.yaml' #数据集anchors文件head

anchors_mask: [ [ 6, 7, 8 ], [ 3, 4, 5 ], [ 0, 1, 2 ] ]

input_shape: [ 416,416 ]

confidence: 0.5 #置信度
nms_iou: 0.3 #nms iou阈值
letterbox_image: False #是否使用letterbox缩放

cuda: True

minoverlap: 0.5 #map计算中的iou阈值

#onnx export config
batch_size: 1
onnx_model: model_data/head.onnx
trt_model: model_data/head.trt