object:
  person:
    dataset_root: '/home/cv/AI_Data/person_yolo'
    model_path: 'weights/person.pth' #模型权重路径
    #    model_path: 'weights/person_spp.pth' #模型权重路径
    classes_path: 'data/person_classes.yaml' #数据类别文件
    anchors_path: 'data/person_anchors.yaml' #数据集anchors文件
  head:
    dataset_root: '/home/cv/AI_Data/head_datas_yolo' #数据集根目录
    model_path: 'weights/head.pth'
    #    model_path: 'weights/head_spp.pth'
    classes_path: 'data/head_classes.yaml' #数据类别文件
    anchors_path: 'data/head_anchors.yaml' #数据集anchors文件head
  helmet:
    dataset_root: '/home/cv/AI_Data/HardHatWorker_voc'
    model_path: 'weights/HardHatWorker.pth' #模型权重路径
    classes_path: 'data/HardHatWorker_classes.yaml' #数据类别文件
    anchors_path: 'data/HardHatWorker_anchors.yaml' #数据集anchors文件
  reflective:
    dataset_root: '/home/cv/AI_Data/reflective'
    model_path: 'weights/reflective.pth' #预加载yolov3权重文件
    classes_path: 'data/reflective_classes.yaml' #数据集类别文件
    anchors_path: 'data/reflective_anchors.yaml' #数据集聚类anchors


cuda: True
obj_type: head

spp: [ ] #不使用SPP 则设为[]
#spp: [ 5,9,13 ]
#activation: mish #leakyrelu or mish
activation: leakyrelu #leakyrelu or mish
anchors_mask: [ [ 6, 7, 8 ], [ 3, 4, 5 ], [ 0, 1, 2 ] ]

input_shape: [ 416,416 ]
#input_shape: [ 608,608 ]

batch_size: 1

confidence: 0.5 #置信度
nms_iou: 0.3 #nms iou阈值
letterbox_image: False #是否使用letterbox缩放

minoverlap: 0.5 #map计算中的iou阈值

onnx_model: data/yolov3_new_spp.onnx
trt_model: data/head.trt