object:
  reflective:
    dataset_root: '/home/cv/AI_Data/reflective'
    model_path: 'weights/reflective-ep124-loss4.193.pth' #预加载yolov3权重文件
    classes_path: 'data/reflective_classes.yaml' #数据集类别文件
    anchors_path: 'data/reflective_anchors.yaml' #数据集聚类anchors
  person:
    dataset_root: '/home/cv/AI_Data/person_yolo'
    model_path: 'weights/person.pth' #预加载yolov3权重文件
    classes_path: 'data/person_classes.yaml' #数据集类别文件
    anchors_path: 'data/person_anchors.yaml' #数据集聚类anchors
  widerperson:
    dataset_root: '/home/cv/AI_Data/widerperson'
    model_path: 'weights/person.pth' #预加载yolov3权重文件
    classes_path: 'data/widerperson_classes.yaml' #数据集类别文件
    anchors_path: 'data/widerperson_anchors.yaml' #数据集聚类anchors
  helmet:
    dataset_root: '/home/cv/AI_Data/yolo_helmet_train\\anno'
    model_path: 'weights/helmet.pth' #预加载yolov3权重文件
    classes_path: 'data/helmet_classes.yaml' #数据类别文件
    anchors_path: 'data/helmet_anchors.yaml' #数据集anchors文件
  head:
    dataset_root: '/home/cv/AI_Data/head_datas_yolo' #数据集根目录
    model_path: 'weights/head.pth'
    classes_path: 'data/head_classes.yaml' #数据类别文件
    anchors_path: 'data/head_anchors.yaml' #数据集anchors文件head

year: '2007'
obj_type: person

cuda: True
num_workers: 8

spp: True
activation: mish
mosaic: True
cosine_lr: True
label_smoothing: 0

Init_Epoch: 0
input_shape: [ 416, 416 ] #模型输入图片尺度
#input_shape: [ 608,608 ] #模型输入图片尺度
anchors_mask: [ [ 6, 7, 8 ], [ 3, 4, 5 ], [ 0, 1, 2 ] ]

#generate config
train_percent: 0.9
trainval_percent: 0.9

Freeze_Train: True
#冻结训练参数设置
Freeze_Epoch: 10
Freeze_batch_size: 16
Freeze_lr: 1e-3
#全网络训练参数设置
UnFreeze_Epoch: 50
Unfreeze_batch_size: 16
Unfreeze_lr: 1e-4

#训练数据集路径文件
train_annotation_path: '2007_train.txt'
val_annotation_path: '2007_val.txt'


