object:
  reflective:
    dataset_root: '/home/cv/AI_Data/reflective'
    model_path: 'home/ubuntu/PycharmProjects/YOLOV3-PyTorch-Simlple-Train/weights/reflective-ep124-loss4.193.pth' #预加载yolov3权重文件
    classes_path: 'home/ubuntu/PycharmProjects/YOLOV3-PyTorch-Simlple-Train/data/reflective_classes.yaml' #数据集类别文件
    anchors_path: 'home/ubuntu/PycharmProjects/YOLOV3-PyTorch-Simlple-Train/data/reflective_anchors.yaml' #数据集聚类anchors
  person:
    dataset_root: '/home/cv/AI_Data/person_yolo'
    #    model_path: 'home/ubuntu/PycharmProjects/YOLOV3-PyTorch-Simlple-Train/weights/person.pth' #预加载yolov3权重文件
    model_path: '' #预加载yolov3权重文件
    classes_path: 'home/ubuntu/PycharmProjects/YOLOV3-PyTorch-Simlple-Train/data/person_classes.yaml' #数据集类别文件
    anchors_path: 'home/ubuntu/PycharmProjects/YOLOV3-PyTorch-Simlple-Train/data/person_anchors.yaml' #数据集聚类anchors
  widerperson:
    dataset_root: '/home/cv/AI_Data/widerperson'
    model_path: 'home/ubuntu/PycharmProjects/YOLOV3-PyTorch-Simlple-Train/weights/person.pth' #预加载yolov3权重文件
    classes_path: 'home/ubuntu/PycharmProjects/YOLOV3-PyTorch-Simlple-Train/data/widerperson_classes.yaml' #数据集类别文件
    anchors_path: 'home/ubuntu/PycharmProjects/YOLOV3-PyTorch-Simlple-Train/data/widerperson_anchors.yaml' #数据集聚类anchors
  helmet:
    dataset_root: '/home/cv/AI_Data/yolo_helmet_train\\anno'
    model_path: 'home/ubuntu/PycharmProjects/YOLOV3-PyTorch-Simlple-Train/weights/helmet.pth' #预加载yolov3权重文件
    classes_path: 'home/ubuntu/PycharmProjects/YOLOV3-PyTorch-Simlple-Train/data/helmet_classes.yaml' #数据类别文件
    anchors_path: 'home/ubuntu/PycharmProjects/YOLOV3-PyTorch-Simlple-Train/data/helmet_anchors.yaml' #数据集anchors文件
  head:
    dataset_root: '/home/cv/AI_Data/head_datas_yolo' #数据集根目录
    model_path: ''
    classes_path: 'home/ubuntu/PycharmProjects/YOLOV3-PyTorch-Simlple-Train/data/head_classes.yaml' #数据类别文件
    anchors_path: 'home/ubuntu/PycharmProjects/YOLOV3-PyTorch-Simlple-Train/data/head_anchors.yaml' #数据集anchors文件head

year: '2007'
obj_type: person

cuda: True
num_workers: 8

#spp: [ ] #不使用SPP 则设为[]
spp: [ 5,9,13 ]
activation: mish #leakyrelu or mish
#activation: leakyrelu #leakyrelu or mish
mosaic: False
cosine_lr: True
label_smoothing: 0 #if label_smoothing=0:不适用平滑标签

Init_Epoch: 0
#input_shape: [ 416, 416 ] #模型输入图片尺度
input_shape: [ 608,608 ] #模型输入图片尺度
anchors_mask: [ [ 6, 7, 8 ], [ 3, 4, 5 ], [ 0, 1, 2 ] ]

#generate config
train_percent: 0.9
trainval_percent: 0.9

Freeze_Train: False
#冻结训练参数设置
Freeze_Epoch: 10
Freeze_batch_size: 16
Freeze_lr: 1e-3
#全网络训练参数设置
UnFreeze_Epoch: 120
Unfreeze_batch_size: 8
Unfreeze_lr: 1e-4

#训练数据集路径文件
train_annotation_path: '2007_train.txt'
val_annotation_path: '2007_val.txt'


