dataset_root: '/home/cv/data/reflective'
model_path: 'weights/reflective-ep124-loss4.193.pth' #预加载yolov3权重文件
classes_path: 'cfg/voc/classes.yaml' #数据集类别文件
anchors_path: 'cfg/voc/anchors.yaml' #数据集聚类anchors
cuda: True
num_workers: 8

spp: [ ] #不使用SPP 则设为[]
#spp: [ 5,9,13 ]
#activation: mish #leakyrelu or mish
activation: leakyrelu #leakyrelu or mish
mosaic: False
label_smoothing: 0 #if label_smoothing=0:不适用平滑标签

Init_Epoch: 0
input_shape: [ 416, 416 ] #模型输入图片尺度
#input_shape: [ 608,608 ] #模型输入图片尺度
anchors_mask: [ [ 6, 7, 8 ], [ 3, 4, 5 ], [ 0, 1, 2 ] ]

#generate config
train_percent: 0.9
trainval_percent: 0.9

Freeze_Train: True

#冻结训练参数设置
Freeze_Epoch: 50
Freeze_batch_size: 16
Freeze_lr: 1e-3

#全网络训练参数设置
UnFreeze_Epoch: 100
Unfreeze_batch_size: 8
Unfreeze_lr: 1e-4

#new args:
Init_lr: 1e-2
optimizer_type: "sgd"
momentum: 0.937
weight_decay: 5e-4
lr_decay_type: "cos"

#训练数据集路径文件
train_file: 'train.txt'
val_file: 'val.txt'
